export const TIME_ENUM = {
  PAST: "PAST",
  FUTURE: "FUTURE",
};

export const MOOD_ENUM = {
  DEPRESSION: "DEPRESSION",
  ANGER: "ANGER",
  SHAME: "SHAME",
  REGRETS: "REGRETS",
  TRAUMA: "TRAUMA",
  ADDICTIONS: "ADDICTIONS",
  PARANOIA: "PARANOIA",
  ANXIETY: "ANXIETY",
  FEAR: "FEAR",
  ANTICIPATION: "ANTICIPATION",
  WORRY: "WORRY",
  STRESS: "STRESS",
};
