export const TIME_ENUM = {
  PAST: "PAST",
  FUTURE: "FUTURE",
};

export const MOOD_ENUM = {
  DEPRESSION: "DEPRESSION", //PAST
  ANGER: "ANGER", //PAST
  SHAME: "SHAME", //PAST
  REGRETS: "REGRETS", //PAST,
  ADDICTIONS: "ADDICTIONS", //PAST
  PARANOIA: "PARANOIA", //PAST
  ANXIETY: "ANXIETY", //FUTURE
  FEAR_OF_UNCERTAINTY: "FEAR_OF_UNCERTAINTY", //FUTURE
  ANTICIPATION: "ANTICIPATION", //FUTURE
  WORRY: "WORRY", //PAST
  STRESS: "STRESS", //FUTURE
};
